policy: "MlpPolicy"
total_timesteps: 2000000
n_steps: 2048
batch_size: 64
n_epochs: 10
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.01
vf_coef: 0.5
learning_rate: 3.0e-4
tensorboard_log: "./tensorboard_logs"
model_save_path: "./models/ppo_racing"
